services:
  bot:
    image: nick395/anime-tracker:latest
    command: bun run start:bot
    environment:
      - TELEGRAM_BOT_TOKEN
      - CONVEX_URL
    restart: unless-stopped

  scraper:
    image: nick395/anime-tracker:latest
    command: bun run start:scraper
    environment:
      - CONVEX_URL
    restart: unless-stopped

